apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameplatform-usuarios
  labels:
    app: gameplatform-usuarios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gameplatform-usuarios
  template:
    metadata:
      labels:
        app: gameplatform-usuarios
    spec:
      containers:
      - name: gameplatform-usuarios
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: gameplatform-usuarios-secret
