apiVersion: v1
kind: Service
metadata:
  name: gameplatform-usuarios
spec:
  type: LoadBalancer
  selector:
    app: gameplatform-usuarios
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
