name: CI/CD da API de Usuarios

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: brunolazzara/gameplatform-usuarios-fiap

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar pacotes
      run: dotnet restore GamePlatform.Usuarios.sln

    - name: Build
      run: dotnet build GamePlatform.Usuarios.sln --configuration Release --no-restore

   # - name: Testes
   #   run: dotnet test GamePlatform.Usuarios.Tests/GamePlatform.Usuarios.Tests.csproj --verbosity normal

  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          push: true

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy para o Azure Container Apps
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     resourceGroup: 'gameplatform'
      #     containerAppName: 'gameplatform-usuarios-api'
      #     imageToDeploy: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      #     targetPort: 8080
      #     location: 'brazilsouth'
      #     containerAppEnvironment: 'gameplatform-apis'
          
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Criar/atualizar secrets no AKS
        run: |
          kubectl create secret generic gameplatform-usuarios-secret \
            --from-literal=ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}" \
            --from-literal=Jwt__Key="${{ secrets.JWT_SECRET }}" \
            --from-literal=Jwt__Issuer="${{ secrets.JWT_ISSUER }}" \
            --from-literal=Jwt__Audience="${{ secrets.JWT_AUDIENCE }}" \
            --from-literal=NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
            --from-literal=NEW_RELIC_APP_NAME="${{ secrets.NEW_RELIC_APP_NAME }}" \
            --from-literal=WEBSITES_ENABLE_APP_SERVICE_STORAGE="${{ secrets.WEBSITES_ENABLE_APP_SERVICE_STORAGE }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy para o AKS
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
